### ISSUE TITLE
Sorry I can't find the example data "rede1.txt"

### ISSUE THREAD

**Issue by liaojiahui-r** [marmello77/network-significance#2]
I am trying to run the code "How to estimate P-values of network metrics and compare pairs of networks using Monte Carlo procedures.R" but I can't find the example data "rede1.txt"

<img width="1022" alt="截屏2020-08-10 19 21 36" src="https://user-images.githubusercontent.com/61280250/89777741-d66acc00-db3e-11ea-9c83-f58a39e885c9.png">
<img width="1552" alt="截屏2020-08-10 19 18 32" src="https://user-images.githubusercontent.com/61280250/89777748-db2f8000-db3e-11ea-8ee6-c47153c0e78f.png">

**Comment by marmello77** [comment]
I'm sorry, that was a translation error, as the original code and example files were written in Portuguese, and then translated into English. Actually, rede1 = net1, rede2 = net2.

**Comment by marmello77** [comment]
I've corrected the code. Thank you for pointing out my error.

**Comment by liaojiahui-r** [comment]
Thank you very much! You're so nice!

But there is a new issue when I generating “null model” `null` with the data "net1":

WARNING: net1 is `"... not a probability matrix! I will proceed after transforming the entries according to option 'autotransform': equiprobable !"`

But still, I got some results: `nestedness nestedness nestedness nestedness nestedness nestedness nestedness nestedness nestedness nestedness 
         0         NA          0          0          0          0          0         NA          0          0`

and, when do `plot(density(null), ...)`,

ERROR: `Error in density.default(null) : 'x' contains missing values`

Could you please give me any suggestion? Thank for your time.

<img width="1050" alt="截屏2020-08-10 20 37 09" src="https://user-images.githubusercontent.com/61280250/89783642-df14cf80-db49-11ea-84a0-de642c151709.png">

**Comment by marmello77** [comment]
You're welcome. It's been a while since I last used this first method (Dormann), as I prefer to use our customized solution (Muylaert & Dododonov). Probably, there has been some change in the package bipartite related to the index "nestedness", used in our example. I've changed it to another nestedness metric, "NODF", and the code ran smoothly. Try it this way, please.

**Comment by liaojiahui-r** [comment]
Thanks! "NODF" works! ^_^
